In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [2]:
df = pd.read_csv("../data/raw/australia_cost_of_living_numbeo_FINAL.csv")

In [3]:
df.shape

(8, 56)

In [4]:
df.head()

,city,numbeo_update_date,restaurant_inexpensive,restaurant_midrange_two,mcdonalds_combo,domestic_draft_beer,imported_beer,cappuccino,soft_drink,water_033l,...,mens_business_shoes,rent_1br_city_centre,rent_1br_outside_centre,rent_3br_city_centre,rent_3br_outside_centre,buy_price_sqm_city_centre,buy_price_sqm_outside_centre,average_monthly_net_salary,mortgage_interest_rate,data_status
0,Sydney,15-Aug-2026,25.0,124.0,16.00,10.5,10.0,5.48,3.88,3.12,...,180.36,3517.50,2403.33,6990.00,3987.08,18395.00,11274.69,6010.70,5.81,complete
1,Melbourne,17-Aug-2026,25.0,115.0,17.00,14.0,12.0,5.71,4.43,3.59,...,185.33,2411.13,1979.54,4815.08,3500.73,10026.39,9020.78,6286.11,5.65,complete
2,Brisbane,17-Aug-2026,25.0,120.0,16.00,12.0,12.0,6.20,4.08,3.44,...,154.62,2890.19,2018.44,4969.15,3410.42,11891.06,8759.42,5950.63,6.01,complete
3,Perth,14-Aug-2026,29.0,122.5,15.38,12.0,12.0,6.08,4.05,3.15,...,224.00,2711.62,2272.00,3951.36,3070.00,11887.22,8149.92,6085.66,5.96,complete
4,Adelaide,15-Aug-2026,25.0,120.0,16.00,11.0,12.5,5.74,4.08,3.63,...,191.25,2518.00,1930.00,3504.00,2690.00,14595.38,9915.46,5494.61,6.07,complete

In [5]:
df.columns.tolist()

['city',
 'numbeo_update_date',
 'restaurant_inexpensive',
 'restaurant_midrange_two',
 'mcdonalds_combo',
 'domestic_draft_beer',
 'imported_beer',
 'cappuccino',
 'soft_drink',
 'water_033l',
 'milk_1l',
 'bread_500g',
 'rice_1kg',
 'eggs_12',
 'local_cheese_1kg',
 'chicken_1kg',
 'beef_1kg',
 'apples_1kg',
 'bananas_1kg',
 'oranges_1kg',
 'tomatoes_1kg',
 'potatoes_1kg',
 'onions_1kg',
 'lettuce_1head',
 'water_15l',
 'wine_midrange',
 'domestic_beer_05l',
 'imported_beer_033l',
 'cigarettes_20',
 'transport_one_way',
 'transport_monthly_pass',
 'taxi_start',
 'taxi_per_km',
 'taxi_wait_hour',
 'gasoline_1l',
 'utilities_85sqm',
 'mobile_plan',
 'internet',
 'gym_membership',
 'tennis_hour',
 'cinema_ticket',
 'preschool_monthly',
 'international_primary_annual',
 'jeans',
 'summer_dress',
 'nike_running_shoes',
 'mens_business_shoes',
 'rent_1br_city_centre',
 'rent_1br_outside_centre',
 'rent_3br_city_centre',
 'rent_3br_outside_centre',
 'buy_price_sqm_city_centre',
 'buy_price_sqm_outside_centre',
 'average_monthly_net_salary',
 'mortgage_interest_rate',
 'data_status']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 56 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   city                          8 non-null      str
 1   numbeo_update_date            8 non-null      str
 2   restaurant_inexpensive        8 non-null      float64
 3   restaurant_midrange_two       8 non-null      float64
 4   mcdonalds_combo               8 non-null      float64
 5   domestic_draft_beer           8 non-null      float64
 6   imported_beer                 8 non-null      float64
 7   cappuccino                    8 non-null      float64
 8   soft_drink                    8 non-null      float64
 9   water_033l                    8 non-null      float64
 10  milk_1l                       8 non-null      float64
 11  bread_500g                    8 non-null      float64
 12  rice_1kg                      8 non-null      float64
 13  eggs_12                       8 non-null      float64
 14  local_cheese_1kg              8 non-null      float64
 15  chicken_1kg                   8 non-null      float64
 16  beef_1kg                      8 non-null      float64
 17  apples_1kg                    8 non-null      float64
 18  bananas_1kg                   8 non-null      float64
 19  oranges_1kg                   8 non-null      float64
 20  tomatoes_1kg                  8 non-null      float64
 21  potatoes_1kg                  8 non-null      float64
 22  onions_1kg                    8 non-null      float64
 23  lettuce_1head                 8 non-null      float64
 24  water_15l                     8 non-null      float64
 25  wine_midrange                 8 non-null      float64
 26  domestic_beer_05l             8 non-null      float64
 27  imported_beer_033l            8 non-null      float64
 28  cigarettes_20                 8 non-null      float64
 29  transport_one_way             8 non-null      float64
 30  transport_monthly_pass        8 non-null      float64
 31  taxi_start                    8 non-null      float64
 32  taxi_per_km                   8 non-null      float64
 33  taxi_wait_hour                8 non-null      float64
 34  gasoline_1l                   8 non-null      float64
 35  utilities_85sqm               8 non-null      float64
 36  mobile_plan                   8 non-null      float64
 37  internet                      8 non-null      float64
 38  gym_membership                8 non-null      float64
 39  tennis_hour                   8 non-null      float64
 40  cinema_ticket                 8 non-null      float64
 41  preschool_monthly             8 non-null      float64
 42  international_primary_annual  8 non-null      float64
 43  jeans                         8 non-null      float64
 44  summer_dress                  8 non-null      float64
 45  nike_running_shoes            8 non-null      float64
 46  mens_business_shoes           8 non-null      float64
 47  rent_1br_city_centre          8 non-null      float64
 48  rent_1br_outside_centre       8 non-null      float64
 49  rent_3br_city_centre          8 non-null      float64
 50  rent_3br_outside_centre       8 non-null      float64
 51  buy_price_sqm_city_centre     8 non-null      float64
 52  buy_price_sqm_outside_centre  8 non-null      float64
 53  average_monthly_net_salary    8 non-null      float64
 54  mortgage_interest_rate        8 non-null      float64
 55  data_status                   8 non-null      str
dtypes: float64(53), str(3)
memory usage: 3.6 KB

In [7]:
df.isnull().sum()

city                            0
numbeo_update_date              0
restaurant_inexpensive          0
restaurant_midrange_two         0
mcdonalds_combo                 0
domestic_draft_beer             0
imported_beer                   0
cappuccino                      0
soft_drink                      0
water_033l                      0
milk_1l                         0
bread_500g                      0
rice_1kg                        0
eggs_12                         0
local_cheese_1kg                0
chicken_1kg                     0
beef_1kg                        0
apples_1kg                      0
bananas_1kg                     0
oranges_1kg                     0
tomatoes_1kg                    0
potatoes_1kg                    0
onions_1kg                      0
lettuce_1head                   0
water_15l                       0
wine_midrange                   0
domestic_beer_05l               0
imported_beer_033l              0
cigarettes_20                   0
transport_one_way               0
transport_monthly_pass          0
taxi_start                      0
taxi_per_km                     0
taxi_wait_hour                  0
gasoline_1l                     0
utilities_85sqm                 0
mobile_plan                     0
internet                        0
gym_membership                  0
tennis_hour                     0
cinema_ticket                   0
preschool_monthly               0
international_primary_annual    0
jeans                           0
summer_dress                    0
nike_running_shoes              0
mens_business_shoes             0
rent_1br_city_centre            0
rent_1br_outside_centre         0
rent_3br_city_centre            0
rent_3br_outside_centre         0
buy_price_sqm_city_centre       0
buy_price_sqm_outside_centre    0
average_monthly_net_salary      0
mortgage_interest_rate          0
data_status                     0
dtype: int64

In [8]:
df.isnull().sum().sum()

np.int64(0)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["city"].duplicated().sum()

np.int64(0)

In [11]:
df["city"].tolist()

['Sydney',
 'Melbourne',
 'Brisbane',
 'Perth',
 'Adelaide',
 'Canberra',
 'Hobart',
 'Darwin']

In [12]:
numeric_cols = df.select_dtypes(include="number").columns

(df[numeric_cols] < 0).sum().sum()

np.int64(0)

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
restaurant_inexpensive,8.0,26.62500,2.013348,25.00,25.0000,25.750,27.8750,30.00
restaurant_midrange_two,8.0,123.50000,5.161672,115.00,120.0000,123.250,127.8750,130.00
mcdonalds_combo,8.0,15.79750,0.660773,15.00,15.2850,16.000,16.0000,17.00
domestic_draft_beer,8.0,11.75000,1.133893,10.50,10.8750,12.000,12.0000,14.00
imported_beer,8.0,12.00000,1.439246,10.00,11.5000,12.000,12.7500,14.00
cappuccino,8.0,5.80375,0.228594,5.48,5.7075,5.745,5.8475,6.20
soft_drink,8.0,4.32500,0.362885,3.88,4.0725,4.255,4.5275,4.95
water_033l,8.0,3.47000,0.296407,3.12,3.1650,3.515,3.6800,3.83
milk_1l,8.0,2.48625,0.235611,2.17,2.3275,2.480,2.5750,2.93
bread_500g,8.0,4.13875,0.438323,3.52,3.7375,4.240,4.4150,4.70
rice_1kg,8.0,3.25000,0.444362,2.66,2.9725,3.185,3.4550,4.00
eggs_12,8.0,7.62500,0.653846,6.34,7.4225,7.655,8.0725,8.49
local_cheese_1kg,8.0,15.03375,2.470639,12.42,13.1725,14.545,15.9425,19.68
chicken_1kg,8.0,13.21125,1.017187,12.00,12.4250,13.135,13.6475,15.23
beef_1kg,8.0,21.31250,3.905340,13.00,19.8575,22.220,23.8025,25.00
apples_1kg,8.0,5.58125,0.552771,4.46,5.5000,5.665,5.8000,6.34
bananas_1kg,8.0,4.39125,0.216692,4.00,4.2900,4.395,4.5475,4.67
oranges_1kg,8.0,4.61000,0.419864,3.98,4.2450,4.720,4.8250,5.20
tomatoes_1kg,8.0,7.01500,0.321736,6.49,6.8525,7.075,7.2200,7.47
potatoes_1kg,8.0,4.19875,0.403394,3.67,3.9475,4.180,4.5100,4.71
onions_1kg,8.0,3.40750,0.339947,2.79,3.3000,3.415,3.5675,3.87
lettuce_1head,8.0,3.48000,0.272973,3.00,3.2900,3.560,3.6400,3.84
water_15l,8.0,2.30750,0.570607,1.72,1.8775,2.190,2.5450,3.23
wine_midrange,8.0,19.20000,1.422272,17.00,18.0000,19.500,20.2000,20.80
domestic_beer_05l,8.0,7.84250,2.719599,5.83,6.6100,7.185,7.5875,14.39
imported_beer_033l,8.0,7.53000,1.838245,5.00,6.5850,7.455,8.1225,11.00
cigarettes_20,8.0,60.18250,5.191531,52.00,57.3750,62.995,63.9900,63.99
transport_one_way,8.0,3.53125,2.117771,0.00,2.7500,4.450,4.7375,5.50
transport_monthly_pass,8.0,130.98500,61.177011,30.00,107.4225,136.400,154.5000,217.39
taxi_start,8.0,5.39625,0.675361,4.30,5.0000,5.325,5.8300,6.50
taxi_per_km,8.0,2.27750,0.371705,1.87,2.0300,2.200,2.3725,3.00
taxi_wait_hour,8.0,56.73000,8.829347,43.32,54.1400,58.400,60.4500,70.00
gasoline_1l,8.0,1.85750,0.074402,1.74,1.8175,1.855,1.9225,1.95
utilities_85sqm,8.0,291.51125,30.363288,251.40,261.8900,299.625,319.9075,320.71
mobile_plan,8.0,40.96375,4.527588,35.08,38.5725,40.410,43.0725,48.33
internet,8.0,83.43000,4.614199,78.50,79.3925,83.035,87.3100,89.00
gym_membership,8.0,89.46000,21.662372,53.17,78.2700,86.105,105.4950,117.20
tennis_hour,8.0,30.36375,7.986061,18.33,27.0100,30.690,35.9000,40.00
cinema_ticket,8.0,24.00000,1.035098,22.50,23.0000,24.250,25.0000,25.00
preschool_monthly,8.0,3103.71375,261.291121,2761.00,2925.0825,3062.085,3304.4225,3500.56
international_primary_annual,8.0,28197.19625,10934.662982,12000.00,19752.0750,29564.285,34309.1000,45289.30
jeans,8.0,111.63375,5.824250,103.90,108.7550,110.160,112.9600,121.25
summer_dress,8.0,78.83875,13.959210,60.77,68.6050,78.595,83.7625,103.00
nike_running_shoes,8.0,161.07375,8.703096,150.00,152.5225,163.280,167.4175,171.79
mens_business_shoes,8.0,187.97125,19.706424,154.62,179.9525,187.405,193.4375,224.00
rent_1br_city_centre,8.0,2704.23625,361.953336,2411.13,2496.3625,2559.000,2756.2625,3517.50
rent_1br_outside_centre,8.0,2138.97500,201.159613,1930.00,1977.1550,2065.130,2304.8325,2426.67
rent_3br_city_centre,8.0,4450.92000,1207.598136,3080.00,3780.9975,4187.900,4853.5975,6990.00
rent_3br_outside_centre,8.0,3137.14000,519.862541,2330.00,2801.6675,3170.000,3432.9975,3987.08
buy_price_sqm_city_centre,8.0,12762.65500,4065.401789,5439.33,11422.0125,12378.960,15196.5350,18395.00
buy_price_sqm_outside_centre,8.0,9164.64625,2012.936086,5000.00,8607.0450,9468.120,10307.5600,11274.69
average_monthly_net_salary,8.0,5984.32375,228.226278,5494.61,5941.6900,6017.590,6091.1275,6286.11
mortgage_interest_rate,8.0,5.98625,0.179598,5.65,5.9225,6.030,6.0875,6.20

In [14]:
df.describe().T[["min", "max"]]

                                   min       max
restaurant_inexpensive           25.00     30.00
restaurant_midrange_two         115.00    130.00
mcdonalds_combo                  15.00     17.00
domestic_draft_beer              10.50     14.00
imported_beer                    10.00     14.00
cappuccino                        5.48      6.20
soft_drink                        3.88      4.95
water_033l                        3.12      3.83
milk_1l                           2.17      2.93
bread_500g                        3.52      4.70
rice_1kg                          2.66      4.00
eggs_12                           6.34      8.49
local_cheese_1kg                 12.42     19.68
chicken_1kg                      12.00     15.23
beef_1kg                         13.00     25.00
apples_1kg                        4.46      6.34
bananas_1kg                       4.00      4.67
oranges_1kg                       3.98      5.20
tomatoes_1kg                      6.49      7.47
potatoes_1kg                      3.67      4.71
onions_1kg                        2.79      3.87
lettuce_1head                     3.00      3.84
water_15l                         1.72      3.23
wine_midrange                    17.00     20.80
domestic_beer_05l                 5.83     14.39
imported_beer_033l                5.00     11.00
cigarettes_20                    52.00     63.99
transport_one_way                 0.00      5.50
transport_monthly_pass           30.00    217.39
taxi_start                        4.30      6.50
taxi_per_km                       1.87      3.00
taxi_wait_hour                   43.32     70.00
gasoline_1l                       1.74      1.95
utilities_85sqm                 251.40    320.71
mobile_plan                      35.08     48.33
internet                         78.50     89.00
gym_membership                   53.17    117.20
tennis_hour                      18.33     40.00
cinema_ticket                    22.50     25.00
preschool_monthly              2761.00   3500.56
international_primary_annual  12000.00  45289.30
jeans                           103.90    121.25
summer_dress                     60.77    103.00
nike_running_shoes              150.00    171.79
mens_business_shoes             154.62    224.00
rent_1br_city_centre           2411.13   3517.50
rent_1br_outside_centre        1930.00   2426.67
rent_3br_city_centre           3080.00   6990.00
rent_3br_outside_centre        2330.00   3987.08
buy_price_sqm_city_centre      5439.33  18395.00
buy_price_sqm_outside_centre   5000.00  11274.69
average_monthly_net_salary     5494.61   6286.11
mortgage_interest_rate            5.65      6.20

In [15]:
df.describe().T[["min", "max"]].to_string()

'                                   min       max\nrestaurant_inexpensive           25.00     30.00\nrestaurant_midrange_two         115.00    130.00\nmcdonalds_combo                  15.00     17.00\ndomestic_draft_beer              10.50     14.00\nimported_beer                    10.00     14.00\ncappuccino                        5.48      6.20\nsoft_drink                        3.88      4.95\nwater_033l                        3.12      3.83\nmilk_1l                           2.17      2.93\nbread_500g                        3.52      4.70\nrice_1kg                          2.66      4.00\neggs_12                           6.34      8.49\nlocal_cheese_1kg                 12.42     19.68\nchicken_1kg                      12.00     15.23\nbeef_1kg                         13.00     25.00\napples_1kg                        4.46      6.34\nbananas_1kg                       4.00      4.67\noranges_1kg                       3.98      5.20\ntomatoes_1kg                      6.49      7.47\npotatoes_1kg                      3.67      4.71\nonions_1kg                        2.79      3.87\nlettuce_1head                     3.00      3.84\nwater_15l                         1.72      3.23\nwine_midrange                    17.00     20.80\ndomestic_beer_05l                 5.83     14.39\nimported_beer_033l                5.00     11.00\ncigarettes_20                    52.00     63.99\ntransport_one_way                 0.00      5.50\ntransport_monthly_pass           30.00    217.39\ntaxi_start                        4.30      6.50\ntaxi_per_km                       1.87      3.00\ntaxi_wait_hour                   43.32     70.00\ngasoline_1l                       1.74      1.95\nutilities_85sqm                 251.40    320.71\nmobile_plan                      35.08     48.33\ninternet                         78.50     89.00\ngym_membership                   53.17    117.20\ntennis_hour                      18.33     40.00\ncinema_ticket                    22.50     25.00\npreschool_monthly              2761.00   3500.56\ninternational_primary_annual  12000.00  45289.30\njeans                           103.90    121.25\nsummer_dress                     60.77    103.00\nnike_running_shoes              150.00    171.79\nmens_business_shoes             154.62    224.00\nrent_1br_city_centre           2411.13   3517.50\nrent_1br_outside_centre        1930.00   2426.67\nrent_3br_city_centre           3080.00   6990.00\nrent_3br_outside_centre        2330.00   3987.08\nbuy_price_sqm_city_centre      5439.33  18395.00\nbuy_price_sqm_outside_centre   5000.00  11274.69\naverage_monthly_net_salary     5494.61   6286.11\nmortgage_interest_rate            5.65      6.20'

In [16]:
pd.set_option("display.max_rows", None)

display(df.describe().T[["min", "max"]])

                                   min       max
restaurant_inexpensive           25.00     30.00
restaurant_midrange_two         115.00    130.00
mcdonalds_combo                  15.00     17.00
domestic_draft_beer              10.50     14.00
imported_beer                    10.00     14.00
cappuccino                        5.48      6.20
soft_drink                        3.88      4.95
water_033l                        3.12      3.83
milk_1l                           2.17      2.93
bread_500g                        3.52      4.70
rice_1kg                          2.66      4.00
eggs_12                           6.34      8.49
local_cheese_1kg                 12.42     19.68
chicken_1kg                      12.00     15.23
beef_1kg                         13.00     25.00
apples_1kg                        4.46      6.34
bananas_1kg                       4.00      4.67
oranges_1kg                       3.98      5.20
tomatoes_1kg                      6.49      7.47
potatoes_1kg                      3.67      4.71
onions_1kg                        2.79      3.87
lettuce_1head                     3.00      3.84
water_15l                         1.72      3.23
wine_midrange                    17.00     20.80
domestic_beer_05l                 5.83     14.39
imported_beer_033l                5.00     11.00
cigarettes_20                    52.00     63.99
transport_one_way                 0.00      5.50
transport_monthly_pass           30.00    217.39
taxi_start                        4.30      6.50
taxi_per_km                       1.87      3.00
taxi_wait_hour                   43.32     70.00
gasoline_1l                       1.74      1.95
utilities_85sqm                 251.40    320.71
mobile_plan                      35.08     48.33
internet                         78.50     89.00
gym_membership                   53.17    117.20
tennis_hour                      18.33     40.00
cinema_ticket                    22.50     25.00
preschool_monthly              2761.00   3500.56
international_primary_annual  12000.00  45289.30
jeans                           103.90    121.25
summer_dress                     60.77    103.00
nike_running_shoes              150.00    171.79
mens_business_shoes             154.62    224.00
rent_1br_city_centre           2411.13   3517.50
rent_1br_outside_centre        1930.00   2426.67
rent_3br_city_centre           3080.00   6990.00
rent_3br_outside_centre        2330.00   3987.08
buy_price_sqm_city_centre      5439.33  18395.00
buy_price_sqm_outside_centre   5000.00  11274.69
average_monthly_net_salary     5494.61   6286.11
mortgage_interest_rate            5.65      6.20

In [17]:
df.dtypes

city                                str
numbeo_update_date                  str
restaurant_inexpensive          float64
restaurant_midrange_two         float64
mcdonalds_combo                 float64
domestic_draft_beer             float64
imported_beer                   float64
cappuccino                      float64
soft_drink                      float64
water_033l                      float64
milk_1l                         float64
bread_500g                      float64
rice_1kg                        float64
eggs_12                         float64
local_cheese_1kg                float64
chicken_1kg                     float64
beef_1kg                        float64
apples_1kg                      float64
bananas_1kg                     float64
oranges_1kg                     float64
tomatoes_1kg                    float64
potatoes_1kg                    float64
onions_1kg                      float64
lettuce_1head                   float64
water_15l                       float64
wine_midrange                   float64
domestic_beer_05l               float64
imported_beer_033l              float64
cigarettes_20                   float64
transport_one_way               float64
transport_monthly_pass          float64
taxi_start                      float64
taxi_per_km                     float64
taxi_wait_hour                  float64
gasoline_1l                     float64
utilities_85sqm                 float64
mobile_plan                     float64
internet                        float64
gym_membership                  float64
tennis_hour                     float64
cinema_ticket                   float64
preschool_monthly               float64
international_primary_annual    float64
jeans                           float64
summer_dress                    float64
nike_running_shoes              float64
mens_business_shoes             float64
rent_1br_city_centre            float64
rent_1br_outside_centre         float64
rent_3br_city_centre            float64
rent_3br_outside_centre         float64
buy_price_sqm_city_centre       float64
buy_price_sqm_outside_centre    float64
average_monthly_net_salary      float64
mortgage_interest_rate          float64
data_status                         str
dtype: object

In [18]:
df["city"].duplicated().sum()

np.int64(0)

In [19]:
df["city"].tolist()

['Sydney',
 'Melbourne',
 'Brisbane',
 'Perth',
 'Adelaide',
 'Canberra',
 'Hobart',
 'Darwin']

In [20]:
numeric_cols = df.select_dtypes(include="number").columns

outlier_summary = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outlier_summary[col] = ((df[col] < lower) | (df[col] > upper)).sum()

pd.Series(outlier_summary).sort_values(ascending=False)

taxi_wait_hour                  3
cappuccino                      3
mens_business_shoes             2
jeans                           2
apples_1kg                      2
taxi_per_km                     1
transport_monthly_pass          1
imported_beer_033l              1
domestic_beer_05l               1
onions_1kg                      1
beef_1kg                        1
mortgage_interest_rate          1
eggs_12                         1
rent_1br_city_centre            1
average_monthly_net_salary      1
rent_3br_city_centre            1
domestic_draft_beer             1
buy_price_sqm_outside_centre    1
buy_price_sqm_city_centre       1
gym_membership                  0
utilities_85sqm                 0
mobile_plan                     0
internet                        0
tennis_hour                     0
nike_running_shoes              0
cinema_ticket                   0
rent_3br_outside_centre         0
preschool_monthly               0
international_primary_annual    0
gasoline_1l                     0
rent_1br_outside_centre         0
summer_dress                    0
restaurant_inexpensive          0
taxi_start                      0
transport_one_way               0
mcdonalds_combo                 0
imported_beer                   0
soft_drink                      0
water_033l                      0
milk_1l                         0
bread_500g                      0
rice_1kg                        0
local_cheese_1kg                0
chicken_1kg                     0
bananas_1kg                     0
oranges_1kg                     0
tomatoes_1kg                    0
potatoes_1kg                    0
lettuce_1head                   0
water_15l                       0
wine_midrange                   0
restaurant_midrange_two         0
cigarettes_20                   0
dtype: int64

In [21]:
flagged_cols = pd.Series(outlier_summary)
flagged_cols = flagged_cols[flagged_cols > 0].index

df[["city"] + list(flagged_cols)]

,city,domestic_draft_beer,cappuccino,eggs_12,beef_1kg,apples_1kg,onions_1kg,domestic_beer_05l,imported_beer_033l,transport_monthly_pass,taxi_per_km,taxi_wait_hour,jeans,mens_business_shoes,rent_1br_city_centre,rent_3br_city_centre,buy_price_sqm_city_centre,buy_price_sqm_outside_centre,average_monthly_net_salary,mortgage_interest_rate
0,Sydney,10.5,5.48,7.70,23.43,5.23,3.50,5.83,5.85,217.39,2.29,57.32,108.47,180.36,3517.50,6990.00,18395.00,11274.69,6010.70,5.81
1,Melbourne,14.0,5.71,8.49,21.64,5.95,3.87,7.61,7.07,198.00,2.00,43.32,110.64,185.33,2411.13,4815.08,10026.39,9020.78,6286.11,5.65
2,Brisbane,12.0,6.20,7.22,19.85,5.75,3.35,7.28,6.83,30.00,2.62,58.80,119.50,154.62,2890.19,4969.15,11891.06,8759.42,5950.63,6.01
3,Perth,12.0,6.08,7.49,19.86,6.34,2.79,6.22,5.00,140.00,2.04,58.00,108.85,224.00,2711.62,3951.36,11887.22,8149.92,6085.66,5.96
4,Adelaide,11.0,5.74,8.07,24.92,5.59,3.46,7.58,8.73,120.00,2.11,44.60,103.90,191.25,2518.00,3504.00,14595.38,9915.46,5494.61,6.07
5,Canberra,12.0,5.77,7.61,22.80,5.71,3.77,6.74,7.92,132.80,2.29,61.80,109.68,189.48,2485.45,4424.44,17000.00,11180.23,6107.53,6.05
6,Hobart,12.0,5.70,8.08,25.00,4.46,3.15,7.09,7.84,140.00,3.00,60.00,110.78,178.73,2600.00,3080.00,12866.86,10016.67,5914.87,6.20
7,Darwin,10.5,5.75,6.34,13.00,5.62,3.37,14.39,11.00,69.69,1.87,70.00,121.25,200.00,2500.00,3873.33,5439.33,5000.00,6024.48,6.14

In [22]:
for col in flagged_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower) | (df[col] > upper)][["city", col]]
    
    print(f"\n{col}")
    print(outliers.to_string(index=False))

domestic_draft_beer
     city  domestic_draft_beer
Melbourne                 14.0

cappuccino
    city  cappuccino
  Sydney        5.48
Brisbane        6.20
   Perth        6.08

eggs_12
  city  eggs_12
Darwin     6.34

beef_1kg
  city  beef_1kg
Darwin      13.0

apples_1kg
  city  apples_1kg
 Perth        6.34
Hobart        4.46

onions_1kg
 city  onions_1kg
Perth        2.79

domestic_beer_05l
  city  domestic_beer_05l
Darwin              14.39

imported_beer_033l
  city  imported_beer_033l
Darwin                11.0

transport_monthly_pass
    city  transport_monthly_pass
Brisbane                    30.0

taxi_per_km
  city  taxi_per_km
Hobart          3.0

taxi_wait_hour
     city  taxi_wait_hour
Melbourne           43.32
 Adelaide           44.60
   Darwin           70.00

jeans
    city  jeans
Brisbane 119.50
  Darwin 121.25

mens_business_shoes
    city  mens_business_shoes
Brisbane               154.62
   Perth               224.00

rent_1br_city_centre
  city  rent_1br_city_centre
Sydney                3517.5

rent_3br_city_centre
  city  rent_3br_city_centre
Sydney                6990.0

buy_price_sqm_city_centre
  city  buy_price_sqm_city_centre
Darwin                    5439.33

buy_price_sqm_outside_centre
  city  buy_price_sqm_outside_centre
Darwin                        5000.0

average_monthly_net_salary
    city  average_monthly_net_salary
Adelaide                     5494.61

mortgage_interest_rate
     city  mortgage_interest_rate
Melbourne                    5.65

In [23]:
df["numbeo_update_date"] = pd.to_datetime(
    df["numbeo_update_date"],
    format="%d-%b-%Y"
)

df[["city", "numbeo_update_date"]]

        city numbeo_update_date
0     Sydney         2026-08-15
1  Melbourne         2026-08-17
2   Brisbane         2026-08-17
3      Perth         2026-08-14
4   Adelaide         2026-08-15
5   Canberra         2026-08-17
6     Hobart         2026-08-01
7     Darwin         2026-07-10

In [24]:
df["numbeo_update_date"].isna().sum()

np.int64(0)

In [25]:
output_path = "../data/processed/australia_cost_of_living_clean.csv"

df.to_csv(output_path, index=False)

print(f"Cleaned dataset saved to: {output_path}")

Cleaned dataset saved to: ../data/processed/australia_cost_of_living_clean.csv